= Informes da Congregação (22/10)
:page-categories: [informe]
:page-excerpt: Repasses do representante discente da Congregação,
acerca da reunião de 22/10.
:toc: macro

toc::[]

== Continuidade do Ensino Remoto Emergencial (ERE)

Barrera (diretor) informa previsões pessimistas da reunião 
dos dirigentes ocorrida na terça-feira. Primeiro semestre do 
ano que vem será, a princípio, remoto.

Carlinhos (presidente da CG) disse que o pró-reitor de graduação 
estava evasivo sobre o próximo semestre na última reunião. Foi 
aprovado calendário de graduação pro ano que vem, com aulas do 
primeiro semestre de 12/4 a 31/7. O segundo semestre se iniciando 
uma semana depois, dia 9/8, com aulas indo até o fim de ano e 
se encerrando no começo de janeiro (após uma pausa de fim de 
ano).

== Reformas no IME-USP

Diretor informou que houve a pintura da parte externa dos 
blocos A e B, tendo um papel mais de restauração, e uma 
tentativa de "harmonização estética" entre os prédios.

Obras com dinheiro da SEF (uma das superintendências da 
reitoria) - como a restauração do teto do CEC e a adequação 
do bloco B às normas do corpo de bombeiros - continuam paradas, 
por medo de falta de recursos.

== Novo site do IME-USP

Site novo do IME entrou no ar. Pós e CG sofreram com isso, 
mas às coisas tão se ajeitando. Reclamações/sugestões podem 
ser levadas ao diretor.

== Aplicativo COMVC

Lançado o aplicativo "COMVC", de alguns departamentos da 
Faculdade de Medicina da USP, para auxiliar no acompanhamento 
da saúde mental das pessoas.

== Posicionamento do MAT em relação ao PL627/2020

Foi aprovada também uma carta do MAT contra a PL627 (mais uma 
do DÓria pra ferrar o orçamento da USP e da FAPESP), a ser 
enviada para os deputados da Assembleia Legislativa como 
aprovada na Congregação. https://drive.google.com/file/d/1rKFw_c5vubzdToSDugF1HdwhX00KU4kv/view?usp=sharing[Leia a carta na íntegra.] 

Para ver o PL: https://www.al.sp.gov.br/propositura/?id=1000337240.
