= Instalação de catracas no Bloco B revogada
:page-categories: [informe]
:revdate: 2020-10-10
:page-excerpt: Reunião de 08/10 do CTA revoga a instalação de catracas no bloco B do IME-USP.
:toc: macro

toc::[]

No último dia 23/09, foi convocada uma reunião extraordinária do Conselho Técnico Administrativo (CTA) com o objetivo de informar uma alteração no orçamento inicial das catracas. Essa alteração incluía um aumento significativo do preço, devido a especificações de peças, necessárias para a utilização do sistema da USP. Os membros do CTA como um todo não gostaram dessa notícia, e mesmo sabendo que o preço final de compra seria provavelmente bem inferior ao orçamento total do IME, a votação que havia sido 7x1 a favor da instalação, passou a ser 3x1 e 4 abstenções, com o representante discente mantendo o voto contrário e os chefes dos 4 departamentos se abstendo.

Após esse resultado, na reunião seguinte, dia 8/10, o diretor trouxe a proposta da desautorização de instalação das catracas, explicando que o momento atual deve ser de união, frente aos planos do governador João Dória que trazem grande perigo ao orçamento da USP, e assim uma decisão tão dividida como a da reunião anterior poderia vir a causar atritos desnecessários, prejudiciais especialmente na atual situação. O momento é de se unir na luta contra o PL529/2020, de modo que a desautorização foi aprovada por unanimidade, e o bloco B continuará sem catracas por enquanto.
