= Informes da Reunião com o Diretor
:page-categories: [informe]
:page-excerpt: Informes sobre a reunião com o diretor Junior Barrera a certo da continuidade do EAD, possibilidade de reoferecimento de disciplinas e projeto de disponibilização de livros digitais como forma de apoio aos estudos.
:toc: macro

Olá comunidade IMEana,

Seguem os informes da reunião com o diretor Junior Barrera e o presidente da 
Comissão de Graduação (CG) Carlos Ferreira.

toc::[]

== Padronização do ensino à distância

O diretor e o presidente da CG concordam que a padronização do ensino à 
distância é razoável e se comprometeram a comunicar e orientar o corpo docente 
a utilizarem preferencialmente as plataformas institucionais - como o Google 
Meet e e-Disciplinas. Além disso, irão mapear quem e quantos são os docentes 
com dificuldade em acessar e utilizar as tecnologias visando dar suporte e 
capacitação para os mesmos.

== Suporte de infraestrutura ao corpo docente

O diretor tem encaminhado compras de mesa digitalizado e um projeto de suporte 
de webcam a base de cano PVC, que permite gravar papel na mesa (a servir como 
"gravação de lousa"), para serem distribuídos aos docentes que indicaram 
necessitar de apoio à infraestrutura. Além disso, disponibilizaram câmeras e 
alocaram funcionários para gravarem aulas no IME-USP para os docentes que assim 
desejarem. Para ter acesso a esses auxílios é necessário que o docente entre em 
contato com o diretor, coisa que o Barrera diz não ter conseguido fazer de 
forma efetiva, isto é, o diretor relata não estar conseguindo se comunicar com 
o corpo docente. Desta forma, pede auxílio do corpo estudantil para fazer esta 
tarefa, então caso o professor não esteja dando um EaD razoável (aula grava ou 
"lousa" gravada), avise-o dessas possibilidades e peça para que entre em 
contato com o diretor ou avise ao CAMat quem é o professor que nós fazeremos a 
comunicação.

== Orientação ao corpo docente quanto a métodos avaliativos

O Barrera e o Carlos afirmam que encaminharam aos docentes orientações quanto a 
que métodos adotarem e como utilizar o e-Disciplinas para disponibilizar 
métodos avaliativos. Contudo, reconhecem que esta comunicação possa não ter 
sido efetiva.

== Matérias que não deram continuidade

Quando apresentado o fato de que ainda há docentes que não estão ministrando 
aulas, Barrera disse "o reitor não puniria, eu puniria". O Carlinhos disse que 
já tem questões sendo encaminhadas, como o caso da turma de estatística do 
Magalhães que será realocada numa turma extra, e disse que irá encaminhar a 
questão do cálculo I da turma 47, pois não estavam ciente do ocorrido. Caso 
esteja matriculado em alguma disciplina que ainda não deu seguimento de forma 
on-line, informe os Representantes Discente ou o CAMat.

== Reoferecimento de disciplinas

Há a possibilidade de reoferecimento, isto é, abrir turma extra de disciplina 
que não seria normalmente oferecida neste período, contudo isto está 
condicionado a demanda. Caso haja uma demanda razoável, o presidente da CG 
ficou de conversar com chefe de departamento responsável para abrir turma extra e, portanto, oferecer a disciplina requisitada.

Informe a demanda:: https://forms.gle/TVTW81GYvLL49hBd6

== Tempo de conclusão de curso e coeficiente de rendimento (CR)

Não haverá acréscimo de tempo ao período ideal de conclusão de curso e este 
semestre entrará, sim, para a contabilização do coeficiente de rendimento.

== Novo calendário letivo (final do primeiro semestre e início do segundo semestre)

Carlos expôs que aquele novo calendário encaminhado pelo diretor na terça-feira 
não é condizente à realidade do IME-USP. Com isso, o presidente da CG já 
esboçou proposta de calendário cujo final do primeiro semestre ficaria para 
final de agosto. Este novo calendário está sendo pensando em contato com a 
presidente da CG da Faculdade de Educação e o presidente da CG do Instituto de 
Física. Ainda é necessário que o calendário seja aprovado pela pró-reitoria, 
após isso acontecer o presidente da CG fará um comunicado aos estudantes

== Pré-requisitos de disciplinas

Os pré-requisitos estão valendo e caso queira cursar disciplina que não tenha 
feito o pré-requisito, deverá pedir por requerimento e estes serão avaliados de forma flexível. Contudo, se você está matriculado no primeiro semestre em um 
pré-requisito da matéria do segundo semestre que deseja cursar, ao solicitar a 
disciplina na interação de matrícula o pedido será aceito.

== Biblioteca e material de apoio aos estudos

Não há previsão para a reabertura da biblioteca. Porém há projeto para fornecer 
material de apoio aos estudos para o corpo estudantil: compra de livros 
digitais, que serão entregues acesso aos estudantes. A dificuldade, contudo 
afirma o Barrera, é saber por meio do corpo docente quais os livros serão 
usados nas disciplinas do segundo semestre.

== Acesso à internet e a equipamento

Não tem acesso a internet? Não tem equipamento adequado? Fale com o CAMat 
através de: https://forms.gle/39vdid9oZ5VWEf7H8

Atenciosamente,
Diretoria do CAMat

